# Generated by Django 3.1.5 on 2021-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_product_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
