# Generated by Django 3.1.5 on 2021-01-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_product_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fruit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_legume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_meat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegetable',
            field=models.BooleanField(default=False),
        ),
    ]
