# Generated by Django 3.1.5 on 2021-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210115_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_grain',
            field=models.BooleanField(default=False),
        ),
    ]
