# Generated by Django 3.1.5 on 2021-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_is_grain'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_dairy',
            field=models.BooleanField(default=False),
        ),
    ]
